sport:
    resource: "@SportBundle/Controller/"
    type:     annotation
    prefix:   /

intro:
    resource: "@IntroBundle/Controller/"
    type:     annotation
    prefix:   /

app:
  resource: '@AppBundle/Controller/'
  type: annotation
