<?php

namespace SportBundle\Repository;

/**
 * VsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VsRepository extends \Doctrine\ORM\EntityRepository
{
}
